# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoVideoStrem' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoVideoStrem
  pod 'PLPlayerKit'
  pod 'SYCacheFileViewController'

  target 'DemoVideoStremTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoVideoStremUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
